---
title: "Lab 7 Rank-Based Test"
author: "Karan Shetty"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

hello this is steve


Its VAN and I am going to make a Histogram 
```{r}

library(tidyverse)

kermit <- read_csv("kermit.csv")

# I created a histogram!
kermit_hist <- ggplot(kermit, aes(x = Score.pre))+
  geom_histogram() +
  facet_wrap(~ Gender)

<<<<<<< HEAD
kermit_hist

=======
kermit_hist 
>>>>>>> 2af3e47da1969e391cf05179e5d28339d3d1b598
```


Teysa : doing some rank based test

```{r}

# Is there a significant difference in pre-talk Kermit scores for males and females?

# Unpaired: Mann Whitney U (because we're only looking at pre-talk scores, NOT pre vs. post test)

mwu_kermit <- kermit %>% 
  wilcox.test(Score.pre ~ Gender, data = .) #wilcox.test was made before piping existed so you must specify "data= ." which says use the most recent data frame

mwu_kermit

# No significant difference between pre-talk Kermit scores for males and females (because p-value is greater than 0.05). 

```


Is there a significant difference in Kermit ranks for pre-talk and post-talk scores (ignoring all other variables)

Null: Nah

```{r}

wsr_kermit = wilcox.test(kermit$Score.pre, kermit$Score.post, paired = TRUE)

wsr_kermit

# There is no significant difference in kermit rankings before and after his talk (summary....)


```




